import { Inter } from 'next/font/google'
import './styles/globals.css'
import {Navbar} from "@/app/layouts/Navbar";
import {Footer} from "@/app/layouts/Footer";


export const metadata = {
  title: 'Login & Sign up Suma',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
      {children}
      </body>
    </html>
  )
}
